### PR TITLE
Added warning about resource leakage

### PR DESCRIPTION
**Pull request by eskimor**
This just caused a server outage for us, so I believe, there should be at least a warning.

### CODE REVIEW

**Comment by eskimor** [comment]
I just realized there is such a warning in the code already, nevertheless others might miss it too.

**Comment by TomMD** [comment]
Hurm, yes that should be a loud warning.  I'll merge that but I should really show this package and the underlying entropy package a little attention.

Turning this ticket into a stream of thought for anyone who is interested in commenting.  This thought folds in a long-standing intent to close on an agreement with those who are strongly anti-DRBG.

One solution would be to use a non-file handle method of getting random numbers.  This isn't really an option if we use `/dev/urandom` but it is an option if randoms come from Linux's `getrandom` or DRBG.  I could make a flag-driven option in the Entropy package to that effect  `-fgetRandom` and it's complement `-fonly_urandom`.

I don't know of any windows solutions to the problem.  The `only_urandom` flag could actually be `no_drbg` and that translates into a matching change for Windows.

Windows: Use cryptoapi + drbg or just cryptoapi (`-fno-drbg`)
Linux: Use getRandom + drbg or just getRandom (`-fno-drbg`)
OS X, FreeBSD, qnx etc can still use urandom with or without drbg.

**Comment by cartazio** [comment]
What's wrong with closing the handle ?

**Comment by eskimor** [comment]
Then the application would crash, it uses lazy IO for getting new random values in pure code.

**Pull request merged**
